apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-file-storage-deployment
  namespace: $TARGET_NAMESPACE
spec:
  selector:
    matchLabels:
      app: secure-file-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: secure-file-storage
    spec:
# Uncomment only if you aren't deploying to the default namespace, remove #
# In this case, make sure to create a Docker registry secret
#      imagePullSecrets:
#        - name: $IMAGE_PULL_SECRET
      containers:
      - name: secure-file-storage-container
        image: $IMAGE_REPOSITORY:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
         - secretRef:
            name: $BASENAME-credentials