apiVersion: v1
kind: Service
metadata:
  name: secure-file-storage-service
  namespace: $TARGET_NAMESPACE
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
  selector:
    app: secure-file-storage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-secure-file-storage
  namespace: $TARGET_NAMESPACE
spec:
  tls:
  - hosts:
    - secure-file-storage.$INGRESS_SUBDOMAIN
    secretName: $INGRESS_SECRET
## Uncomment below if you are using a custom domain. Remove '# '
#   - hosts:
#     - secure-file-storage.$MYDOMAIN
#     secretName: secure-file-storage-certificate
  rules:
  - host: secure-file-storage.$INGRESS_SUBDOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secure-file-storage-service
            port: 
              number: 8081
## Uncomment below if you are using a custom domain. Remove '# '
#   - host: secure-file-storage.$MYDOMAIN
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: secure-file-storage-service
#             port:
#               number: 8081