---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-secure-file-storage-builddeploy
spec:
  params:
    - name: git-repository
      description: The git repo
    - name: git-branch
      description: the branch for the git repo
    - name: schematics-workspace-id
    - name: target-region
    - name: registry-namespace
    - name: registry-region
    - name: image-name
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: sfs-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: secure-file-storage-$(uid)
      spec:
        pipelineRef:
          name: pipeline-build-deploy
        resources:
          - name: app-image
            resourceSpec:
              type: image
        params:
          - name: git-repository
            value: $(params.git-repository)
          - name: git-branch
            value: $(params.git-branch)
          - name: schematics-workspace-id
            value: $(params.schematics-workspace-id)
          - name: target-region
            value: $(params.target-region)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: registry-region
            value: $(params.registry-region)
          - name: image-name
            value: $(params.image-name)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: sfs-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-secure-file-storage-uninstall
spec:
  params:
    - name: schematics-workspace-id
    - name: target-region
    - name: git-repository
    - name: git-branch
    - name: registry-namespace
    - name: registry-region
    - name: image-name    
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: sfs-uninstall-$(uid)
      spec:
        pipelineRef:
          name: pipeline-uninstall
        params:
          - name: schematics-workspace-id
            value: $(params.schematics-workspace-id)
          - name: target-region
            value: $(params.target-region)
          - name: git-repository
            value: $(params.git-repository)
          - name: git-branch
            value: $(params.git-branch)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: registry-region
            value: $(params.registry-region)
          - name: image-name
            value: $(params.image-name)            
        workspaces:
        - name: pipeline-workspace
          emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tb-secure-file-storage-builddeploy
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-listener-builddeploy
spec:
  triggers:
    - binding:
        name: tb-secure-file-storage-builddeploy
      template:
        name: tt-secure-file-storage-builddeploy
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tb-secure-file-storage-uninstall
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-listener-uninstall
spec:
  triggers:
    - binding:
        name: tb-secure-file-storage-uninstall
      template:
        name: tt-secure-file-storage-uninstall